apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
      tiers: web
  template:
    metadata:
      name: admin
      labels:
        app: admin
        tiers: web
    spec:
      containers:
        - name: admin
          image: adminer:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector:
    app: admin
    tiers: web
  ports:
    - protocol: TCP
      port: 8080
  sessionAffinity: ClientIP