apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crmpgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deployment
spec:
  selector:
    matchLabels:
      app: crm
      tiers: bdd
  template:
    metadata:
      name: crm
      labels:
        app: crm
        tiers: bdd
    spec:
      volumes:
        - name: crmpgdata
          persistentVolumeClaim:
            claimName: crmpgdata
      containers:
        - name: crm
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-names
                  key: CRM_DB
                  optional: true
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: crmpgdata
              mountPath: /var/lib/postgresql/18/docker
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: crm
spec:
  selector:
    app: crm
    tiers: bdd
  ports:
    - protocol: TCP
      port: 5432
