services:
    prometheus:
      image: prom/prometheus:latest
      volumes:
        - prometheus-data:/prometheus
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      ports:
        - "9090:9090"

    grafana:
      image: grafana/grafana-enterprise
      volumes:
        - grafana-data:/var/lib/grafana
      ports:
        - "3000:3000"

    db_to_monitor:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=db_to_monitor
      volumes:
        - ./scripts/init_users.sh:/docker-entrypoint-initdb.d/init_users.sh

    db_exporter:
      image: quay.io/prometheuscommunity/postgres-exporter
      environment:
        - DATA_SOURCE_URI=db_to_monitor:5432/postgres?sslmode=disable
        - DATA_SOURCE_USER=postgres
        - DATA_SOURCE_PASS=password
      ports:
        - "9187:9187"
      depends_on:
        - db_to_monitor

volumes:
    prometheus-data:
    grafana-data: