apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todo-api
      tiers: web
  template:
    metadata:
      name: todo-api
      labels:
        app: todo-api
        tiers: web
    spec:
      containers:
        - name: todo-api
          image: todo-api-hexagone:2026
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: tokens
---
apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 3002
