# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mylist.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'mylist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmylist.proto\"\x0f\n\rMyListRequest\"\x1f\n\x0eMyListResponse\x12\r\n\x05\x66iles\x18\x01 \x03(\t29\n\x06MyList\x12/\n\nGiveMyList\x12\x0e.MyListRequest\x1a\x0f.MyListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mylist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYLISTREQUEST']._serialized_start=16
  _globals['_MYLISTREQUEST']._serialized_end=31
  _globals['_MYLISTRESPONSE']._serialized_start=33
  _globals['_MYLISTRESPONSE']._serialized_end=64
  _globals['_MYLIST']._serialized_start=66
  _globals['_MYLIST']._serialized_end=123
# @@protoc_insertion_point(module_scope)
