apiVersion: v1
kind: Pod
metadata:
  name: podvol
spec:
  volumes:
    - name: monsupervolume
      hostPath:
        path: /tmp/monsupervolume
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: monsupervolume
          mountPath: /opt/monsupervol
      
