FROM debian:latest

USER root
RUN apt update && apt install -y openssh-server
RUN useradd --create-home -s /bin/bash test

COPY ./ssh_keys/id_ed25519.pub /home/test/.ssh/authorized_keys
RUN chown -R test:test /home/test/.ssh
RUN chmod 700 /home/test/.ssh
RUN chmod 600 /home/test/.ssh/authorized_keys

USER root
CMD [ "/usr/sbin/sshd", "-D" ]